default['couchbase']['cluster_name'] = 'dev'

default['couchbase']['bucket_name'] = 'cmbucket'
default['couchbase']['bucket_password'] = 'cmpasswd'
default['couchbase']['data_path'] = '/data'
default['couchbase']['index_path'] = '/index'
default['couchbase']['host_name'] = '127.0.0.1'
default['couchbase']['user'] = 'couchbase'
default['couchbase']['group'] = 'couchbase'
default['couchbase']['ram_size'] = '500'
default['couchbase']['port'] = '8091'
default['couchbase']['index_ram_size'] = '500'
default['couchbase']['replicas'] = '1'
default['couchbase']['verison'] = '4.5.1'
default['couchbase']['install_dir'] = '/srv/couchbase'
default['couchbase']['ftp_active_mode'] = true

default['couchbase']['vault'] = ''
default['couchbase']['vault-item'] = ''
default['couchbase']['vault-item-key'] = ''